language: go

# which go versions do we target?
go:
 - 1.5.2
 - tip

notifications:
 email: false

# container based stuffs
sudo: false

addons:
 apt:
   sources:
   - llvm-toolchain-precise-3.7
   - ubuntu-toolchain-r-test

   packages:
   - llvm-3.7
   - llvm-3.7-dev
   - libedit2
   - libedit-dev
   - libconfig++8-dev
   - g++-4.9

install:
 # use g++-4.9 
 - export CXX="g++-4.9"
 # dynamic llvm version fetching that is probably overkill
 - git clone https://github.com/ark-lang/go-llvm.git $GOPATH/src/github.com/ark-lang/go-llvm
 # install the bindings to gopath
 - export CGO_CPPFLAGS="`llvm-config-3.7 --cppflags`"
 - export CGO_LDFLAGS="`llvm-config-3.7 --ldflags --libs --system-libs all`"
 - export CGO_CXXFLAGS=-std=c++11
 - go install -tags byollvm github.com/ark-lang/go-llvm/llvm

# our stuff goes here
script:
 - go get -v -tags byollvm ./...
 - go install -v -tags byollvm ./...
 - $GOPATH/bin/ark-testrunner
